#数据库配置
database:
  type: sqlite
  # sqlite的path
  path: plugins/Pouvoir/database.db
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: root
  table: my_database
  #每10分钟同步一次 （tick）
  user-container-sync-time: 12000
options:
  #调试模式
  debug: false
  #  Asahi-调试模式
  #  debug-asahi: false
  # 会影响所有附属
  number-format: "#.##"
  operation:
    string-append-separator: ", "