custom-handler:
  triggers: [ async player chat ]
  when:
    - if: "'check &player name == 'Glom_'"
      goto: main1
    - else: main
  functions:
    main: |-
      tell &player 你说话了! -  爱来自 plugins/Pouvoir/handlers/simple-handler.yml
    main1: |-
      tell &player Glom说话了!