name: javadoc
on:
  push:
    branches:
      - master
jobs:
  javadoc:
    name: javadoc
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8.0
      - name: build
        run: |-
          chmod +x gradlew
          ./gradlew dokkaJavadoc
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          directory: build/dokka/javadoc